### ISSUE TITLE
t/connection-lost.t failures because of localized or unexpected error messages

### ISSUE THREAD

**Issue by eserte** [jhthorsen/mojo-redis#29]
See subject. On a FreeBSD smoker I see:
```
#   Failed test 'server disappeared'
#   at t/connection-lost.t line 30.
#          got: 'Socket is not connected'
#     expected: 'Connection refused'
# Looks like you failed 1 test of 3.
t/connection-lost.t ...... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests 
```

Or with a non-English locale (probably only for older perls):
```
#   Failed test 'server disappeared'
#   at t/connection-lost.t line 30.
#          got: 'Socket ist nicht verbunden'
#     expected: 'Connection refused'
# Looks like you failed 1 test of 3.
t/connection-lost.t ...... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests 
```
(the translation would also not match)

Another one (a linux system):
```
#   Failed test 'server disappeared'
#   at t/connection-lost.t line 30.
#          got: 'Verbindungsaufbau abgelehnt'
#     expected: 'Connection refused'
# Looks like you failed 1 test of 3.
t/connection-lost.t ...... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests 
```
(here the translation would be correct)

**Comment by jhthorsen** [comment]
I would very much appreciate some help on how to test this. Is it good enough to just do this?

```
ok $err, 'client disconnected';
```

What do you think @Grinnz?

**Comment by Grinnz** [comment]
If these errors are coming from somewhere else and are localized, I'm not sure what else you can do other than control the localization in the tests (which I don't know if it's simple to do)

**Comment by jhthorsen** [comment]
I don't even know how to change the locale 😞

But could I use `setlocale(SOME_TYPE)` to check if the tests should be run? I was thinking something like this:

```
test_err('Premature connection close', 'client disconnected');

sub test_err {
  my $lang = `setlocale(LC_MESSAGES)`;
  return is $err, @_ if $lang eq 'C' or $lang =~ /^en_/;
  return ok $err, $_[1];
}
```

I don't really like how it looks, but maybe I can make it better if I knew how to change the locale and make Perl output messages in different languages.
