### ISSUE TITLE
Protocol::Redis::XS not working with depth > 2 (ie with Streams)

### ISSUE THREAD

**Issue by akarelas** [jhthorsen/mojo-redis#34]
Here's a script to demonstrate:

```perl
#!/usr/bin/env perl

use v5.22;
use warnings;
use FindBin '$RealBin';
use lib "$RealBin/local/lib/perl5";

use Mojo::Redis;
use Mojo::IOLoop;
use Data::Dumper;

print "Use Protocol::Redis::XS? (y/n) ";
chomp(my $ans = <STDIN>);
my $protocol = $ans =~ /^y/i ? 'Protocol::Redis::XS' : 'Protocol::Redis';

my $redis = Mojo::Redis->new(
    protocol_class => $protocol,
    max_connections => 0,
);

Mojo::IOLoop->next_tick(sub {

    my $STREAM = 'foo-'.(int rand 1e8);

    $redis->db->xread_p(BLOCK => 5e3, STREAMS => $STREAM, '$')
        ->then(sub {say Dumper({success => \@_});})
        ->catch(sub {say Dumper({error => \@_})})
    ;

    Mojo::IOLoop->timer(1, sub {
        $redis->db->xadd_p($STREAM, '*', foo => int rand 100);
    });

});

Mojo::IOLoop->start;
```

Output in non-XS case: a normal and expected output

Output in XS case:
```
Mojo::Reactor::EV: I/O watcher failed: No support for nested multi bulk replies with depth > 2 at /somepath/../local/lib/perl5/Mojo/Redis/Connection.pm line 174, <STDIN> line 1.
```

Could you please push this bug up to Protocol::Redis::XS? I'm afraid I don't know enough about Mojo::Redis to explain to that module's author what Mojo::Redis does exactly with Protocol::Redis::XS.

And Protocol::Redis::XS is also mentioned (almost recommended) in Mojo::Redis documentation, so we shouldn't leave it like this (not-working).

**Comment by jhthorsen** [comment]
I've written a test for this now in abfeac8c56ea14a214797a5802b278d82ac71561 and it seems to work with Protocol::Redis, so I suggest you use that until this is resolved.

@dgl: Is this something you can fix in https://github.com/dgl/protocol-redis-xs ?

**Comment by jhthorsen** [comment]
Closing this in favour of https://github.com/dgl/protocol-redis-xs/issues/5

**Comment by akarelas** [comment]
@jhthorsen It seems that the standard bug-reporting mechanism of Protocol::Redis::XS is really RT, and not github, so I think we should report the bug there as well?

https://rt.cpan.org/Public/Dist/Display.html?Name=Protocol-Redis-XS

**Comment by jhthorsen** [comment]
From what I've heard, it seems like a lost case, but you're free to try of course.
