### ISSUE TITLE
Mojo::Redis::PubSub lacks connection management

### ISSUE THREAD

**Issue by kraih** [jhthorsen/mojo-redis#37]
It appears that `Mojo::Redis::PubSub` has no way to reconnect if the connection gets closed. That's a pretty fatal flaw for a module that should be used over long periods of time. So just steal @jberger's code from [Mojo::Pg::PubSub](https://github.com/mojolicious/mojo-pg/blob/master/lib/Mojo/Pg/PubSub.pm).

**Comment by jhthorsen** [comment]
@kraih: So I can use https://github.com/mojolicious/mojo-pg/commit/d9be0850fb3f253f7bbbdf854968a03479c57db5 as a blueprint for how to implement this?

**Comment by jhthorsen** [comment]
Version 3.18 is on it's way to CPAN now.

Enjoy 👍

**Comment by jhthorsen** [comment]
I tried to be consistent with Mojo::Pg, but because the connections are different, I had to do some changes. However, the attribute for controlling the reconnect is called `reconnect_interval` and there's `reconnect` and `disconnect` events.
