### ISSUE TITLE
Find/make/fix an alternative to Protocol::Redis::XS

### ISSUE THREAD

**Issue by jhthorsen** [jhthorsen/mojo-redis#38]
Protocol::Redis::XS has too many limitations, so I'm going to change the default protocol to Protocol::Redis. This is bummer, but I think it's the safest choice for most users.

Keeping this issue open as a reminder that we should have a faster protocol parser.

Related issues:

* #20 - See how a bundled protocol parser would perform compared to Protocol::Redis
* #34 - Protocol::Redis::XS not working with depth > 2
* https://github.com/dgl/protocol-redis-xs/issues/5 - Add support for nested multi bulk replies with depth > 2

**Comment by Grinnz** [comment]
I released https://metacpan.org/pod/Alien::hiredis which I may try to use to make a FFI-based hiredis parser. The problem is that hiredis only includes a reply parser. Protocol::Redis::XS implements the message construction side of the API directly in XS (and this is probably where all the bugs come from). So maybe using hiredis to parse replies and pureperl to construct commands is a good compromise.

**Comment by jhthorsen** [comment]
@Grinnz: Sounds perfect to me! 👍

**Comment by jhthorsen** [comment]
Me and @Grinnz has tried to improve Protcol::Redis, but nothing seems to happen... I think it's time to bundle Mojo::Redis::Protocol, but since I don't really have time now, I'm going to hold it off.

References:

* https://github.com/und3f/protocol-redis/pull/4 - Optimize encode method
* https://github.com/und3f/protocol-redis/pull/8 - Optimize parse method

**Comment by jhthorsen** [comment]
@Grinnz has created https://github.com/Grinnz/Protocol-Redis-Faster, so we'll start using that once it has been released 👍

**Comment by jhthorsen** [comment]
Protocol::Redis::Faster is 116% faster than Protocol::Redis, and 37% slower than Protocol::Redis::XS. I think that's a huge improvement 👍 

```
$ TEST_BENCHMARK=1000 TEST_ONLINE=redis://localhost prove -vl t/benchmark.t

ok 1 - Mojo::Redis/Protocol::Redis 6.28367 wallclock secs ( 6.06 usr +  0.08 sys =  6.14 CPU) @ 162.87/s (n=1000)
ok 2 - Mojo::Redis/Protocol::Redis::Faster 2.96888 wallclock secs ( 2.78 usr +  0.06 sys =  2.84 CPU) @ 352.11/s (n=10
00)
ok 3 - Mojo::Redis/Protocol::Redis::XS 1.91195 wallclock secs ( 1.74 usr +  0.06 sys =  1.80 CPU) @ 555.56/s (n=1000)
ok 4 - Mojo::Redis2/Protocol::Redis 7.55858 wallclock secs ( 7.29 usr +  0.09 sys =  7.38 CPU) @ 135.50/s (n=1000)
ok 5 - Mojo::Redis2/Protocol::Redis::Faster 4.06515 wallclock secs ( 3.86 usr +  0.07 sys =  3.93 CPU) @ 254.45/s (n=1000)
ok 6 - Mojo::Redis2/Protocol::Redis::XS 3.07873 wallclock secs ( 2.89 usr +  0.07 sys =  2.96 CPU) @ 337.84/s (n=1000)

ok 7 - Redis/Faster (2.84s) is not slower than Redis2/Faster (3.93s)
ok 8 - Redis/Faster (2.84s) is not slower than Redis/PP (6.14s)

               Rate Redis2/PP Redis/PP Redis2/Faster Redis2/XS Redis/Faster Redis/XS
Redis2/PP     136/s        --     -17%          -47%      -60%        -62%      -76%
Redis/PP      163/s       20%       --          -36%      -52%        -54%      -71%
Redis2/Faster 254/s       88%      56%            --      -25%        -28%      -54%
Redis2/XS     338/s      149%     107%           33%        --         -4%      -39%
Redis/Faster  352/s      160%     116%           38%        4%          --      -37%
Redis/XS      556/s      310%     241%          118%       64%         58%        --

1..8
ok
All tests successful.
Files=1, Tests=8, 26 wallclock secs ( 0.02 usr  0.00 sys + 25.02 cusr  0.46 csys = 25.50 CPU)
Result: PASS
```

**Comment by Grinnz** [comment]
I've been able to release Protocol::Redis::XS 0.06 with fixes for these issues.
