### ISSUE TITLE
Keyspace/keyevent notifications in Mojo::Redis::PubSub has some issues

### ISSUE THREAD

**Issue by 0xAF** [jhthorsen/mojo-redis#42]
There seems to be a problem with PubSub, when used for notifications (keyspace/keyevent).

Here is a simple script to test: http://sprunge.us/0LKLvX
The output should be:
```
[debug] subscribed channels [__keyevent@*__:expired|__keyevent@__:expired *]
...
[debug] from custom listen: [__keyevent@0__:expired]
```
Here are the problems I see with `keyspace_listen`:
* The generated channel name is missing the DB after the @ character. In my custom listener I've used '*' to match all DBs. So I suggest a change [here](https://github.com/jhthorsen/mojo-redis/blob/master/lib/Mojo/Redis/PubSub.pm#L73) at the end of the line `// ''` to be replaced with `// '*'`
* The generated channel name has `space` and (`star` or `keyname`) at the end. In my experience, this is invalid channel name and we never receive events in this channel. I did some experiments and watched the output of `redis-cli --csv psubscribe "__key*@*__:*"` command. It seems to confirm what is stated in [Redis documentation](https://redis.io/topics/notifications).
    + The Key-space channel receives as message the name of the event.
    + The Key-event channel receives as message the name of the key.

  My experiments confirm that we cannot listen for notifications on operation and key together. We should listen to only one of them, either operation or key, hence keyspace and keyevent channels. So I suggest the line [here](https://github.com/jhthorsen/mojo-redis/blob/master/lib/Mojo/Redis/PubSub.pm#L73) to be replaced from:
`    return sprintf '__%s@%s__:%s %s', $args->{type}, $args->{db} // $self->redis->url->path->[0] // '',
    $args->{type} eq 'keyevent' ? (@$args{qw(op key)}) : (@$args{qw(key op)});
`
  to
`    return sprintf '__%s@%s__:%s', $args->{type}, $args->{db} // $self->redis->url->path->[0] // '*',
$args->{type} eq 'keyevent' ? $args->{op} : $args->{key};
`
  removing the last argument in channel name.

  If I'm incorrect, please advice me how to subscribe to both operation and key.
  But if I'm correct on this and these changes are acceptable, then the parameters on the [keyspace_listen](https://metacpan.org/pod/Mojo::Redis::PubSub#keyspace_listen) should probably be changed from:
`$cb = $pubsub->keyspace_listen($key, $op, sub { my ($pubsub, $message) = @_ }) });
`
  to
`$cb = $pubsub->keyspace_listen($what_to_listen_for, $key_or_event_name, sub { my ($pubsub, $message) = @_ }) });
`
  where we should specify something like `(key|event)` for `$what_to_listen_for` and the key/event name in `$key_or_event_name`. And the `keyspace_listen` method should be reworked for that. Or perhaps there should be more common name like `notifications_listen`, or may be 2 new methods `keyspace_listen` and `keyevent_listen`?

 * Another problem is the received `payload` in the `callback` function. As a `payload` we receive only the channel where the event happened. We should receive the next argument, so we know which key was expired (in the example). So my suggestion is [here](https://github.com/jhthorsen/mojo-redis/blob/master/lib/Mojo/Redis/PubSub.pm#L96) the line:
`for my $cb (@{$self->{chans}{$res->[1]}}) { $self->$cb($res->[2]) }` to be changed with `for my $cb (@{$self->{chans}{$res->[1]}}) { $self->$cb($res->[2], $res->[3]) }`, to include the next argument which is the important one. And the documentation to be updated on this.

Thanks for the great module and the time spent on this.

**Comment by 0xAF** [comment]
If you accept the changes and do not have much time to implement them, I can make a PR in the next days. But it's probably better if you make the changes in the way you feel it correct.

**Comment by jhthorsen** [comment]
Hey. Sorry for the late reply. Yes, I would very much appreciate a PR 👍

**Comment by jhthorsen** [comment]
1. The generated channel name is missing the DB after the @ character
I don't understand that. Look at https://github.com/jhthorsen/mojo-redis/blob/5cfef4175a2b4290cf561d5fa8f0083e882cae2c/t/pubsub.t#L57 - I guess you mean that the DB is there, but when not specifying a DB, you want "*"? If so, why not do `$pubus->keyspace_listen(db => '*')`? I don't think I mind the change to `... // '*'` though.

2. The generated channel name has space and (star or keyname) at the end
This looks like a easy bug to fix. I'll push it right away.

3. The received payload in the callback function
Not quite sure what is the best design, but since it sounds like `keyspace_listen()` is completely broken, then we can make any change I guess.

**Comment by jhthorsen** [comment]
Please have a look at the two commits above.

**Comment by 0xAF** [comment]
>     1. The generated channel name is missing the DB after the @ character
>        I don't understand that.

The problem was in the way we connect to Redis. I was connecting with `my $redis = Mojo::Redis->new();`, leaving the defaults, which should be redis on `localhost` and db `0`.
I see you've fixed that already. And you've fixed the second problem too. Thanks.

Now the payload problem remains. The easiest fix would be what I suggested above (including one more parameter to the CB function, i.e. `$self->$cb($res->[2], $res->[3])`), but I'm not sure it's the best fix. It could be better to return the whole response. I'm not sure if this would be more helpful, but in case there are some responses in redis, that can give more parameters, then the user can decide how much parameters to consume.
I mean [here](https://github.com/jhthorsen/mojo-redis/blob/master/lib/Mojo/Redis/PubSub.pm#L96) we call the CB function like this now `$self->$cb($res->[2])`. It might be better to call it like this `$self->$cb($res)`.
What do you think?

**Comment by jhthorsen** [comment]
I decided to go with `[@$res[2, 3]]`, since it makes the most sense compared to how listen() works today. Hope that works for you.

**Comment by 0xAF** [comment]
Thanks for fixing the bugs. There is nothing to sorry about. It's me that should make excuses. I could have prepared a PR and then discuss over the PR.
