### ISSUE TITLE
Installation fails in t/connection-sentinel.t

### ISSUE THREAD

**Issue by dequid** [jhthorsen/mojo-redis#46]
On Debian (Kernel version `Linux version 3.2.0-4-amd64`) i get:

`Running make test for JHTHORSEN/Mojo-Redis-3.22.tar.gz
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-basic.t ............. ok
t/benchmark.t ............ skipped: TEST_ONLINE=redis://localhost
t/cache-offline.t ........ ok
t/cache.t ................ skipped: TEST_ONLINE=redis://localhost
t/connection-auth.t ...... ok
t/connection-lost.t ...... Can't use string ("ioloop") as a subroutine ref while "strict refs" in use at /usr/local/share/perl/5.14.2/Mojo/Promise.pm line 71.
t/connection-lost.t ...... Dubious, test returned 29 (wstat 7424, 0x1d00)
No subtests run
t/connection-sentinel.t .. Mojo::Reactor::Poll: I/O watcher failed: Can't use string ("ioloop") as a subroutine ref while "strict refs" in use at /usr/local/share/perl/5.14.2/Mojo/Promise.pm line 71.`

The last test will try and loop forever until i CTRL+C

**Comment by dequid** [comment]
Seems like it happens due to the Mojo::Promise constructor change in Mojolicious 8.15
When i downgrade to 8.14, it works fine.

**Comment by jhthorsen** [comment]
This should be fixed now in v3.23. Soon available on CPAN. Thanks for reporting in 👍
