### ISSUE TITLE
Implement a Redis Cluster Support

### ISSUE THREAD

**Issue by xurc** [jhthorsen/mojo-redis#48]
Main cluster commands are the same as the regular Redis server, the difference is that when connecting, a list of cluster nodes is indicated and the data is scattered across the slots/nodes (like based on crc16 from the key, as I managed to peek in the RedisDB::Cluster code). And the module must respond to a cluster nodes configuration change, as is done in the same module.

It is possible that cluster support can be implemented in Protocol::Redis::(Cluster?) namespace.

OR

Maybe is there any other way to add Redis cluster support to Mojo::Redis? Maybe I can somehow redefine the underlying database to RedisDB::Cluster or something else?

**Comment by jhthorsen** [comment]
I don't know to be honest, and I don't have too much time working on this these days unfortunately.

**Comment by jhthorsen** [comment]
I'm going to close this, since I don't see how I would be able to implement this myself.

I will take a PR though!
