### ISSUE TITLE
Can't use EX option of SET command

### ISSUE THREAD

**Issue by rabbiveesh** [jhthorsen/mojo-redis#50]
I'm trying to use redis to set the value of a key with an expire, but without using the SETEX command, seeing as the doc (https://redis.io/commands/set) suggest using the EX option with the SET command.

Either the command doesn't work, or I can't decipher the documentation, but doing
``` perl
$app->redis->db->set('key', 'value', 'PX 9001');
```
will just return ERR syntax error.

When run with MOJO_REDIS_DEBUG set, I get this:
```
[36f6bce1a280c3b32529556e5ff756bf] CONNECTING redis://localhost/0 (blocking=1)
[36f6bce1a280c3b32529556e5ff756bf] <<< (*2\r\n$6\r\nSELECT\r\n$1\r\n0\r\n)
[36f6bce1a280c3b32529556e5ff756bf] <<< (*4\r\n$3\r\nSET\r\n$3\r\nkey\r\n$5\r\nvalue\r\n$7\r\nPX 9001\r\n)
[36f6bce1a280c3b32529556e5ff756bf] >>> (+OK\r\n-ERR syntax error\r\n)
```

For now I'm just going to use the SETEX command, but this is either a bug or a doc problem nonetheless.

I'm having this problem on Mojo::Redis version 3.24, running on perl v5.26 and v5.30

**Comment by Grinnz** [comment]
set takes a list of values, and in the redis protocol 'EX' and the following value are two different values in the command. So `$app->redis->db->set('key', 'value', 'EX', 9001)`

**Comment by rabbiveesh** [comment]
Oh.
Is that but different in the docs, or did I miss something?

**Comment by Grinnz** [comment]
I am not sure if it's specifically documented, but it's how all redis commands work, they take a list of values and the official redis docs show them space separated normally. The redis protocol is very straightforward.
