### ISSUE TITLE
Mojo::Redis2 Link Not Found

### ISSUE THREAD

**Issue by yuki-kimoto** [jhthorsen/mojo-redis#61]
https://metacpan.org/pod/Mojo::Redis

The link of Mojo::Redis2 not found.

**Comment by Grinnz** [comment]
The latest release of Mojo::Redis2 has been deleted from CPAN so it is no longer indexed. @jhthorsen maybe the latest release should be left up to show that it is deprecated & point people to Mojo::Redis?

**Comment by yuki-kimoto** [comment]
@Grinnz 

If Mojo::Redis2 has been deleted, I think it is good to remove Mojo::Redis2 link of Mojo::Redis document.

```
DESCRIPTION

This module is in no way compatible with the 1.xx version of Mojo::Redis

and this version also tries to fix a lot of the confusing methods

in -----> Mojo::Redis2 related to pubsub.

SEE ALSO

------> Mojo::Redis2.
```

**Comment by jhthorsen** [comment]
The broken links has been removed in "master" now.

@Grinnz: I don't really have time to do that, even though it's probably a good idea.
