### ISSUE TITLE
More some Redis command examples

### ISSUE THREAD

**Issue by yuki-kimoto** [jhthorsen/mojo-redis#62]
Can I add a little more some Redis command examples in Blocking section?

```
set
expire
```

**Comment by jhthorsen** [comment]
I added two new examples. The generic rule is that you take the arguments documented on https://redis.io/commands and pass them in as a list. When that is said, you can also check the documentation for Mojo::Redis::Database:

https://metacpan.org/pod/Mojo::Redis::Database#set
