### ISSUE TITLE
Issue with extra commands being sent when connecting to a sentinel cluster

### ISSUE THREAD

**Issue by JamesDooley** [jhthorsen/mojo-redis#64]
I noticed, when trying to add sentinel support to my current code, that the sentinel connection code is running extra commands during the discovery process.  Specifically if I initialize the connection with GET, it will try to run that command during the discovery process.

For example:
my $redis = Mojo::Redis->new('redis://user:pass@mymaster?sentinel=10.0.0.1:26379');
$redis->db->get('Test');

Will produce output like this:
```
[e215835e9157e5532ff8da54be90ab57] SENTINEL DISCOVERY redis://10.0.0.1:26379/1?sentinel=10.0.0.1%3A26379 (blocking=1)
[e215835e9157e5532ff8da54be90ab57] <<< (*2\r\n$4\r\nAUTH\r\n$16\r\pass\r\n)
[e215835e9157e5532ff8da54be90ab57] <<< (*2\r\n$3\r\nGET\r\n$4\r\nTest\r\n)
[e215835e9157e5532ff8da54be90ab57] <<< (*3\r\n$8\r\nSENTINEL\r\n$23\r\nget-master-addr-by-name\r\n$8\r\nmymaster\r\n)
[e215835e9157e5532ff8da54be90ab57] >>> (+OK\r\n-ERR unknown command `GET`, with args beginning with: `Test`, \r\n*2\r\n$11\r\n10.0.0.1\r\n$4\r\n6379\r\n)
```

Looking at the discovery code it looks like the $self->{write} value is being used, but contains the GET command in the array.  The auth section works because it unshifts that command in place and then runs the SENTINEL command separately with write_p which appends the command to the write queue.

I was able to work around this in my testing by moving {write} out of the way when connecting and moving it back when done.  Not really an elegant solution, so I am hoping that there is a better way.

**Comment by jhthorsen** [comment]
Thanks for reporting in. This should be fixed in "master" now and will be available on CPAN later today.
