### ISSUE TITLE
Race condition with sending pubsub notify just after subscription

### ISSUE THREAD

**Issue by Yenya** [jhthorsen/mojo-redis#67]
When handling Redis pubsub messages, I sometimes receive a bare number as a message payload instead of the real message payload someone sent (e.g. the JSON data). It happens when I have more than one channel subscribed, and try to send a message to the channel just after subscribing to it. It seems that the `message` event handler in `Mojo::Redis::Pubsub::_listen()` gets called with `['subscribe', $channel_name, $somenumber]` arrayref, and tries to use it as a pubsub message. The real message is `['message', $channel_name, $payload]`, but the handler only checks whether an arrayref with at least three members was received. I tried to run the test script with MOJO_REDIS_DEBUG=1, and it seems that the message handler gets called with the arrayref representing the last command _sent_ to Redis, instead of _received_ from Redis.

Here is the script to reproduce it - it subscribes three channels, sends the subscription notification to the channel, receives some notifications, and then tries to unsubscribe and subscribe again. Then there is a recurring timer, which sends some more messages. After several seconds or at most few minutes, it dies(). I also tried with a single channel instead of three, but was not able to reproduce the problem then.

```
#!env perl

use Mojo::Base -signatures;
use Mojo::Redis;

my $prefix = "pubsub-test/42";
my $channels = 3;
my $msgs_per_iter = 5; # unsubscribe/subscribe after this # of messages

my $redis = Mojo::Redis->new(shift)
	or die "Can't connect to Redis";

my $pubsub = $redis->pubsub;

sub add_channel($pubsub, $channel) {
	my $msgs = $msgs_per_iter;
	say "Listening on channel $channel for $msgs messages";
	my $cb;
	$cb = $pubsub->listen($channel => sub ($pubsub, $msg) {
		--$msgs;
		say "Received from channel $channel message '$msg' remaining $msgs";
		if ($msg !~ /real_message/) {
			Mojo::IOLoop->reset;
			die "INVALID MESSAGE";
		}

		if ($msgs <= 0) {
			say "Removing subscription to channel $channel cb $cb";
			$pubsub->unlisten("$channel" => $cb);
			add_channel($pubsub, $channel);
		}
	});
	$pubsub->notify($channel => "real_message: subscribing");
}

add_channel($pubsub, "$prefix/$_")
	for 1 .. $channels;

# Generate some messages
Mojo::IOLoop->recurring(1 => sub ($loop) {
	my $msg = "real_message: ping";
	my $channel = $prefix . '/' . (1 + int(rand($channels)));
	say "Broadcasting msg '$msg' to channel $channel";
	$pubsub->notify($channel => $msg);
});

Mojo::IOLoop->start;
```

I have added `use Data::Dumper; say "Response: ", Dumper $res;` near the top of the `message` event handler in `Mojo::Redis::PubSub::_listen()` in order to see what data gets the handler called with.
When I run the above script with MOJO_REDIS_DEBUG=1, the output ends with something like this:

```
Received from channel pubsub-test/42/2 message 'real_message: ping' remaining 1
Broadcasting msg 'real_message: ping' to channel pubsub-test/42/2
[39f083c275b4def015225666d0b26820] <<< (*3\r\n$7\r\nPUBLISH\r\n$16\r\npubsub-test/42/2\r\n$18\r\nreal_message: ping\r\n)
[39f083c275b4def015225666d0b26820] >>> (:1\r\n)
[71ee183d292592cbdcc388ccb182b8a7] >>> (*3\r\n$7\r\nmessage\r\n$16\r\npubsub-test/42/2\r\n$18\r\nreal_message: ping\r\n)
Response: $VAR1 = [
          'message',
          'pubsub-test/42/2',
          'real_message: ping'
        ];

Received from channel pubsub-test/42/2 message 'real_message: ping' remaining 0
Removing subscription to channel pubsub-test/42/2 cb CODE(0x36aaf78)
[71ee183d292592cbdcc388ccb182b8a7] <<< (*2\r\n$11\r\nUNSUBSCRIBE\r\n$16\r\npubsub-test/42/2\r\n)
Listening on channel pubsub-test/42/2 for 5 messages
[71ee183d292592cbdcc388ccb182b8a7] <<< (*2\r\n$9\r\nSUBSCRIBE\r\n$16\r\npubsub-test/42/2\r\n)
[39f083c275b4def015225666d0b26820] <<< (*3\r\n$7\r\nPUBLISH\r\n$16\r\npubsub-test/42/2\r\n$25\r\nreal_message: subscribing\r\n)
[39f083c275b4def015225666d0b26820] >>> (:1\r\n)
[71ee183d292592cbdcc388ccb182b8a7] >>> (*3\r\n$7\r\nmessage\r\n$16\r\npubsub-test/42/2\r\n$25\r\nreal_message: subscribing\r\n*3\r\n$11\r\nunsubscribe\r\n$16\r\npubsub-test/42/2\r\n:2\r\n*3\r\n$9\r\nsubscribe\r\n$16\r\npubsub-test/42/2\r\n:3\r\n)
Response: $VAR1 = [
          'subscribe',
          'pubsub-test/42/2',
          3
        ];

Received from channel pubsub-test/42/2 message '3' remaining 4
Mojo::Reactor::Poll: I/O watcher failed: INVALID MESSAGE at ./pubsub-test.pl line 29.
[0] CLOSED
[0] CLOSED
```

**Comment by jhthorsen** [comment]
I rewrote most of Mojo::Redis::Pubsub now, so I think it should be impossible to get into this situation now.

**Comment by Yenya** [comment]
3.27 works for me. Thanks!
