### ISSUE TITLE
Add an example which uses WATCH/MULTI/EXEC/retry transaction

### ISSUE THREAD

**Issue by Yenya** [jhthorsen/mojo-redis#69]
So far none of the examples provided by Mojo::Redis use the WATCH/MULTI/EXEC/retry transactions of Redis. It would be nice if Mojo::Redis docs were extended with such an example. This is especially complicated if one wants to use the Promise-based asynchronous interface. So far I have the following code which uses a named subroutine for the retry part, but I don't consider it to be nice enough. I can convert it to a pull request, if there isn't a better way to do the asynchronous transactions. I hope there is, though!

```
#!/usr/bin/env perl

use Mojo::Base -signatures;
use Mojo::Redis;
use Data::Dumper;

my $redis = Mojo::Redis->new(shift)
        or die "Can't connect to Redis";

my $db = $redis->db;
my $key = 'testkey';

$db->set($key => 1, EX => 100);

Mojo::IOLoop->timer(1 => sub {
        say "Setting $key = 42 from timer to clash with the running txn";
        $redis->db->set($key => 42);
});

my $retries = 3; # set to 1 for testing the full failure
sub set_in_tx($db, $key, $val) {
        $db->watch_p($key)
        ->then(sub {
                say "watching the key $key and sleeping for a while";
                Mojo::Promise->timer(2);
        })->then(sub {
                say "MULTI";
                $db->multi_p;
        })->then(sub {
                say "setting $key = $val in transaction";
                # Mojo::Promise->all() can be used to wrap more requests
                $db->set_p($key => $val);
        })->then(sub {
                say "trying to commit (EXEC)";
                $db->exec_p;
        })->then(sub {
                if (!defined $_[0]) {
                        say "TXN failed"; 
                        if (--$retries > 0) {
                                say "retrying";
                                set_in_tx($db, $key, $val);
                        } else {
                                die "TXN failed repeatedly";
                        }
                } else {        
                        say "EXEC returned " . Dumper $_[0];
                }
        });
}

set_in_tx($db, $key, 2)->catch(sub { "set_in_tx failed" })->wait;
```

Thanks!

-Yenya

**Comment by jhthorsen** [comment]
I'm not exactly sure what you want...
* Do you want the code you posted above as an example in Mojo::Redis? - I don't think the code sample is a good example, since it includes three parts which makes it a bit confusing.
* Do you want an easier way to do retry? - Retry is hard, and there's many ways to solve it, depending on what the task requires. Because of that, I don't want to include a retry-example.

I don't mind a Mojo::Redis::Guides::Cookbook and I'll consider a PR if you make one, but the cookbook examples should be to the point imo.

**Comment by Yenya** [comment]
Hello,

What I want? I want to have an example how to do a fully asynchronous WATCH/MULTI/EXEC/retry transaction in Mojo::Redis - either in Mojo::Redis docs, or in the Cookbook. In order to acchieve that, I posted my own solution how would I do this, and hope somebody can suggest improvements or a completely different way how to do this. What I find especially ugly in my code is that it requires a named subroutine to do the retry part. Is there a better way?

Thanks,

-Yenya

**Comment by jhthorsen** [comment]
I’m not going to add this, but I might take a PR for a cookbook.
